[tool.black]
line-length = 80

extend-exclude = "cdk.out|node_modules"

[tool.ruff]
line-length = 80
ignore = ["E501"]
extend-select = [
    "I",
    "C4",
    "SIM",
    "Q003",
    "RET",
]
extend-exclude = [
    "cdk.out",
    "/node_modules",
]
